In [15]:
import scipy.io
import numpy as np
import pandas as pd
import os

In [5]:
mat_file_path = "../data_matlab/power_profile_tests/01_powerprofile_10degrees_0capacityreduction.mat"
mat_contents = scipy.io.loadmat(mat_file_path)

mat_contents.keys()

dict_keys(['__header__', '__version__', '__globals__', 'C', 'I', 'None', 'Rp', 'Rs', 'SoC', 'V', 'Vocv', 'battery_capacity', 'capacity_reduction_factor', 'dt', 'temperature', 'time', '__function_workspace__'])

In [7]:
variables_info = {key: type(mat_contents[key]) for key in mat_contents if not key.startswith("__")}
variables_info

{'C': numpy.ndarray,
 'I': numpy.ndarray,
 'None': scipy.io.matlab._mio5_params.MatlabOpaque,
 'Rp': numpy.ndarray,
 'Rs': numpy.ndarray,
 'SoC': numpy.ndarray,
 'V': numpy.ndarray,
 'Vocv': numpy.ndarray,
 'battery_capacity': numpy.ndarray,
 'capacity_reduction_factor': numpy.ndarray,
 'dt': numpy.ndarray,
 'temperature': numpy.ndarray,
 'time': numpy.ndarray}

In [12]:
variables_shapes = {key: mat_contents[key].shape for key in mat_contents if isinstance(mat_contents[key], np.ndarray)}
variables_shapes

{'C': (75001, 1),
 'I': (75001, 1),
 'None': (1,),
 'Rp': (75001, 1),
 'Rs': (75001, 1),
 'SoC': (75001, 1),
 'V': (75001, 1),
 'Vocv': (75001, 1),
 'battery_capacity': (1, 1),
 'capacity_reduction_factor': (1, 1),
 'dt': (1, 1),
 'temperature': (1, 1),
 'time': (1, 1),
 '__function_workspace__': (1, 619464)}

In [13]:
data = {
    "C": mat_contents["C"].flatten(),
    "I": mat_contents["I"].flatten(),
    "Rp": mat_contents["Rp"].flatten(),
    "Rs": mat_contents["Rs"].flatten(),
    "SoC": mat_contents["SoC"].flatten(),
    "V": mat_contents["V"].flatten(),
    "Vocv": mat_contents["Vocv"].flatten(),
}

df = pd.DataFrame(data)

In [14]:
df.head()

              C         I        Rp        Rs       SoC         V      Vocv
0  35942.914665  2.026404  0.001913  0.002511  0.550000  3.727919  3.733064
1  35943.302025  1.902325  0.001913  0.002511  0.549990  3.728173  3.733057
2  35943.665666  2.173937  0.001913  0.002511  0.549980  3.727426  3.733051
3  35944.081227  2.174373  0.001913  0.002511  0.549969  3.727360  3.733043
4  35944.496871  2.175270  0.001913  0.002511  0.549959  3.727295  3.733036

In [16]:
df.describe()

,C,I,Rp,Rs,SoC,V,Vocv
count,75001.000000,75001.000000,75001.000000,75001.000000,75001.000000,75001.000000,75001.000000
mean,42371.458879,-0.160795,0.002256,0.002457,0.550153,3.757818,3.757106
std,13268.840603,4.530576,0.000581,0.000088,0.189935,0.138759,0.137211
min,15904.437713,-16.473376,0.001569,0.002254,0.275658,3.573302,3.582742
25%,36246.113225,0.000004,0.001883,0.002451,0.365985,3.624676,3.627495
50%,39910.542525,1.882306,0.002022,0.002501,0.526206,3.718874,3.717552
75%,52959.279095,2.119529,0.002457,0.002511,0.735662,3.883119,3.884727
max,65486.343782,5.066156,0.003983,0.002536,0.815341,3.980036,3.971419

In [17]:
folder_path = "../data/power_profile_tests"
file_name = "01_powerprofile_10degrees_0capacityreduction.csv"

os.makedirs(folder_path, exist_ok=True)

csv_file_path = os.path.join(folder_path, file_name)
df.to_csv(csv_file_path, index=False)

print(f"CSV file saved at: {csv_file_path}")

CSV file saved at: ../data/power_profile_tests\01_powerprofile_10degrees_0capacityreduction.csv